name: CI

on: 
  push:
    branches:    
      - master 


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: |
        yarn install
    - name: yarn lint
      run: |
        yarn lint
    - name: Unit Testing
      run: |
        yarn test:unit
    - name: End-to-end testing
      run: |
        yarn test:e2e  
      env:
        CI: true
      
    - name: yarn build
      run: |
        yarn run build --if-present