name: Build and test

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 12.x
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node ${{matrix.node-version}}
        uses: actions/setup-node@v1.4.1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: yarn install
      - name: check linting
        run: yarn lint
      - name: test
        run: yarn test